Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-24.04"
    ubuntu.vm.provision "shell", path: "../../scripts/install-samba.sh"
    ubuntu.vm.network "private_network", ip: "192.168.61.2"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.gui = false
    end
  end
end
